use std::collections::HashMap;

/// A document stored in the vector database.
///
/// Documents are the fundamental unit of storage in the RAG system. Each document
/// contains the original text content, its vector embedding for similarity search,
/// and optional metadata for tracking source information.
///
/// # Example
///
/// ```no_run
/// use std::collections::HashMap;
/// # use core::rag::Document;
///
/// let embedding = vec![0.1, 0.2, 0.3];
/// let doc = Document::new("doc_1", "Hello world", embedding)
///     .with_metadata("source", "user_input")
///     .with_metadata("timestamp", "2024-01-01");
/// ```
#[derive(Debug, Clone)]
pub struct Document {
    /// Unique identifier for the document.
    ///
    /// This ID is used to deduplicate documents and track document versions.
    /// Format typically: `{source}_{chunk_index}` for chunked documents.
    pub id: String,
    
    /// The original text content of the document.
    ///
    /// This is the human-readable text that will be retrieved and shown
    /// to the LLM as context when relevant.
    pub content: String,
    
    /// Vector embedding representing the semantic meaning of the content.
    ///
    /// Generated by the embedding model (e.g., nomic-embed-text). The dimensionality
    /// depends on the model used. Used for similarity comparisons during search.
    pub embedding: Vec<f32>,
    
    /// Additional metadata about the document.
    ///
    /// Common metadata keys:
    /// - `source`: Original file path or source identifier
    /// - `chunk`: Chunk index if document was split
    /// - `timestamp`: When the document was added
    /// - `type`: Document type (e.g., "code", "markdown", "text")
    pub metadata: HashMap<String, String>,
}

impl Document {
    /// Creates a new document with the given ID, content, and embedding.
    ///
    /// # Arguments
    ///
    /// * `id` - Unique identifier for this document
    /// * `content` - The text content to store
    /// * `embedding` - Pre-computed vector embedding of the content
    ///
    /// # Example
    ///
    /// ```no_run
    /// # use core::rag::Document;
    /// let embedding = vec![0.1, 0.2, 0.3];
    /// let doc = Document::new("my_doc", "Hello world", embedding);
    /// ```
    pub fn new(
        id: impl Into<String>,
        content: impl Into<String>,
        embedding: Vec<f32>,
    ) -> Self {
        Self {
            id: id.into(),
            content: content.into(),
            embedding,
            metadata: HashMap::new(),
        }
    }
    
    /// Adds metadata to the document using a builder pattern.
    ///
    /// This method consumes and returns self, allowing for method chaining.
    ///
    /// # Arguments
    ///
    /// * `key` - Metadata key (e.g., "source", "chunk")
    /// * `value` - Metadata value
    ///
    /// # Example
    ///
    /// ```no_run
    /// # use core::rag::Document;
    /// let embedding = vec![0.1, 0.2, 0.3];
    /// let doc = Document::new("id", "content", embedding)
    ///     .with_metadata("source", "file.txt")
    ///     .with_metadata("chunk", "0");
    /// ```
    pub fn with_metadata(mut self, key: impl Into<String>, value: impl Into<String>) -> Self {
        self.metadata.insert(key.into(), value.into());
        self
    }
}

/// A search result containing a document and its similarity score.
///
/// Returned by vector search operations, ordered by descending similarity score.
/// Higher scores indicate better matches to the query.
///
/// # Score Range
///
/// Similarity scores typically range from -1.0 to 1.0 when using cosine similarity:
/// - `1.0` - Identical vectors (perfect match)
/// - `0.0` - Orthogonal vectors (no similarity)
/// - `-1.0` - Opposite vectors (completely dissimilar)
///
/// In practice, most scores will be between 0.0 and 1.0 for text embeddings.
#[derive(Debug, Clone)]
pub struct SearchResult {
    /// The document that matched the search query.
    pub document: Document,
    
    /// Similarity score between the query and this document.
    ///
    /// Computed using cosine similarity between the query embedding
    /// and the document embedding. Higher scores indicate better matches.
    pub score: f32,
}
